// Code generated by protoc-gen-go.
// source: cluster.proto
// DO NOT EDIT!

/*
Package serverpb is a generated protocol buffer package.

It is generated from these files:
	cluster.proto

It has these top-level messages:
	ChatMsg
	DataChgSummary
	Node
	NodeChgRequest
	NodeChgResponse
	NodeQryRequest
	NodeQryResponse
	PingRequest
	PingResponse
*/
package serverpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NodeChgRequest_Operations int32

const (
	NodeChgRequest_UNKNOWN NodeChgRequest_Operations = 0
	// A new node request to join the cluster
	NodeChgRequest_JOIN NodeChgRequest_Operations = 1
	// A node request to quit the cluster
	NodeChgRequest_QUIT NodeChgRequest_Operations = 2
	// request to add a node to the server list as a new node just joined
	NodeChgRequest_ADD NodeChgRequest_Operations = 3
	// Request to drop a node from the server list as a node is about to quit
	NodeChgRequest_DROP NodeChgRequest_Operations = 4
)

var NodeChgRequest_Operations_name = map[int32]string{
	0: "UNKNOWN",
	1: "JOIN",
	2: "QUIT",
	3: "ADD",
	4: "DROP",
}
var NodeChgRequest_Operations_value = map[string]int32{
	"UNKNOWN": 0,
	"JOIN":    1,
	"QUIT":    2,
	"ADD":     3,
	"DROP":    4,
}

func (x NodeChgRequest_Operations) String() string {
	return proto.EnumName(NodeChgRequest_Operations_name, int32(x))
}
func (NodeChgRequest_Operations) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type ChatMsg struct {
	Userid  int32  `protobuf:"varint,1,opt,name=userid" json:"userid,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *ChatMsg) Reset()                    { *m = ChatMsg{} }
func (m *ChatMsg) String() string            { return proto.CompactTextString(m) }
func (*ChatMsg) ProtoMessage()               {}
func (*ChatMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type DataChgSummary struct {
	// The number of record received.
	RecordCount int64 `protobuf:"varint,1,opt,name=record_count,json=recordCount" json:"record_count,omitempty"`
	// The duration of the traversal in seconds.
	ElapsedTime uint64 `protobuf:"varint,2,opt,name=elapsed_time,json=elapsedTime" json:"elapsed_time,omitempty"`
}

func (m *DataChgSummary) Reset()                    { *m = DataChgSummary{} }
func (m *DataChgSummary) String() string            { return proto.CompactTextString(m) }
func (*DataChgSummary) ProtoMessage()               {}
func (*DataChgSummary) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Node struct {
	Hostname    string `protobuf:"bytes,1,opt,name=Hostname,json=hostname" json:"Hostname,omitempty"`
	RPCPort     int32  `protobuf:"varint,2,opt,name=RPCPort,json=rPCPort" json:"RPCPort,omitempty"`
	ConsolePort int32  `protobuf:"varint,3,opt,name=ConsolePort,json=consolePort" json:"ConsolePort,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type NodeChgRequest struct {
	Operation NodeChgRequest_Operations `protobuf:"varint,1,opt,name=operation,enum=serverpb.NodeChgRequest_Operations" json:"operation,omitempty"`
	Node      *Node                     `protobuf:"bytes,2,opt,name=node" json:"node,omitempty"`
}

func (m *NodeChgRequest) Reset()                    { *m = NodeChgRequest{} }
func (m *NodeChgRequest) String() string            { return proto.CompactTextString(m) }
func (*NodeChgRequest) ProtoMessage()               {}
func (*NodeChgRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *NodeChgRequest) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type NodeChgResponse struct {
	Fail   bool   `protobuf:"varint,1,opt,name=fail" json:"fail,omitempty"`
	ErrMsg string `protobuf:"bytes,2,opt,name=err_msg,json=errMsg" json:"err_msg,omitempty"`
}

func (m *NodeChgResponse) Reset()                    { *m = NodeChgResponse{} }
func (m *NodeChgResponse) String() string            { return proto.CompactTextString(m) }
func (*NodeChgResponse) ProtoMessage()               {}
func (*NodeChgResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type NodeQryRequest struct {
	ScrNode *Node `protobuf:"bytes,1,opt,name=scrNode" json:"scrNode,omitempty"`
}

func (m *NodeQryRequest) Reset()                    { *m = NodeQryRequest{} }
func (m *NodeQryRequest) String() string            { return proto.CompactTextString(m) }
func (*NodeQryRequest) ProtoMessage()               {}
func (*NodeQryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *NodeQryRequest) GetScrNode() *Node {
	if m != nil {
		return m.ScrNode
	}
	return nil
}

type NodeQryResponse struct {
	Nodes []*Node `protobuf:"bytes,1,rep,name=Nodes,json=nodes" json:"Nodes,omitempty"`
}

func (m *NodeQryResponse) Reset()                    { *m = NodeQryResponse{} }
func (m *NodeQryResponse) String() string            { return proto.CompactTextString(m) }
func (*NodeQryResponse) ProtoMessage()               {}
func (*NodeQryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *NodeQryResponse) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

// A PingRequest specifies the string to echo in response.
// Fields are exported so that they will be serialized in the rpc call.
type PingRequest struct {
	// Echo this string with PingResponse.
	Ping string `protobuf:"bytes,1,opt,name=ping" json:"ping,omitempty"`
	// The address of the client.
	Addr string `protobuf:"bytes,2,opt,name=addr" json:"addr,omitempty"`
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

// A PingResponse contains the echoed ping request string.
type PingResponse struct {
	// An echo of value sent with PingRequest.
	Pong string `protobuf:"bytes,1,opt,name=pong" json:"pong,omitempty"`
}

func (m *PingResponse) Reset()                    { *m = PingResponse{} }
func (m *PingResponse) String() string            { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()               {}
func (*PingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func init() {
	proto.RegisterType((*ChatMsg)(nil), "serverpb.ChatMsg")
	proto.RegisterType((*DataChgSummary)(nil), "serverpb.DataChgSummary")
	proto.RegisterType((*Node)(nil), "serverpb.Node")
	proto.RegisterType((*NodeChgRequest)(nil), "serverpb.NodeChgRequest")
	proto.RegisterType((*NodeChgResponse)(nil), "serverpb.NodeChgResponse")
	proto.RegisterType((*NodeQryRequest)(nil), "serverpb.NodeQryRequest")
	proto.RegisterType((*NodeQryResponse)(nil), "serverpb.NodeQryResponse")
	proto.RegisterType((*PingRequest)(nil), "serverpb.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "serverpb.PingResponse")
	proto.RegisterEnum("serverpb.NodeChgRequest_Operations", NodeChgRequest_Operations_name, NodeChgRequest_Operations_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for SyncUp service

type SyncUpClient interface {
	// DataChange() send data change requests to peers
	DataChange(ctx context.Context, opts ...grpc.CallOption) (SyncUp_DataChangeClient, error)
	// NodeChange send Join or Quit request to other peers
	NodeChange(ctx context.Context, in *NodeChgRequest, opts ...grpc.CallOption) (*NodeChgResponse, error)
	// NodeQuery ask for a list of all nodes
	NodeQuery(ctx context.Context, in *NodeQryRequest, opts ...grpc.CallOption) (*NodeQryResponse, error)
	// Ping peers
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type syncUpClient struct {
	cc *grpc.ClientConn
}

func NewSyncUpClient(cc *grpc.ClientConn) SyncUpClient {
	return &syncUpClient{cc}
}

func (c *syncUpClient) DataChange(ctx context.Context, opts ...grpc.CallOption) (SyncUp_DataChangeClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_SyncUp_serviceDesc.Streams[0], c.cc, "/serverpb.SyncUp/DataChange", opts...)
	if err != nil {
		return nil, err
	}
	x := &syncUpDataChangeClient{stream}
	return x, nil
}

type SyncUp_DataChangeClient interface {
	Send(*ChatMsg) error
	CloseAndRecv() (*DataChgSummary, error)
	grpc.ClientStream
}

type syncUpDataChangeClient struct {
	grpc.ClientStream
}

func (x *syncUpDataChangeClient) Send(m *ChatMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *syncUpDataChangeClient) CloseAndRecv() (*DataChgSummary, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(DataChgSummary)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *syncUpClient) NodeChange(ctx context.Context, in *NodeChgRequest, opts ...grpc.CallOption) (*NodeChgResponse, error) {
	out := new(NodeChgResponse)
	err := grpc.Invoke(ctx, "/serverpb.SyncUp/NodeChange", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncUpClient) NodeQuery(ctx context.Context, in *NodeQryRequest, opts ...grpc.CallOption) (*NodeQryResponse, error) {
	out := new(NodeQryResponse)
	err := grpc.Invoke(ctx, "/serverpb.SyncUp/NodeQuery", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncUpClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := grpc.Invoke(ctx, "/serverpb.SyncUp/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SyncUp service

type SyncUpServer interface {
	// DataChange() send data change requests to peers
	DataChange(SyncUp_DataChangeServer) error
	// NodeChange send Join or Quit request to other peers
	NodeChange(context.Context, *NodeChgRequest) (*NodeChgResponse, error)
	// NodeQuery ask for a list of all nodes
	NodeQuery(context.Context, *NodeQryRequest) (*NodeQryResponse, error)
	// Ping peers
	Ping(context.Context, *PingRequest) (*PingResponse, error)
}

func RegisterSyncUpServer(s *grpc.Server, srv SyncUpServer) {
	s.RegisterService(&_SyncUp_serviceDesc, srv)
}

func _SyncUp_DataChange_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SyncUpServer).DataChange(&syncUpDataChangeServer{stream})
}

type SyncUp_DataChangeServer interface {
	SendAndClose(*DataChgSummary) error
	Recv() (*ChatMsg, error)
	grpc.ServerStream
}

type syncUpDataChangeServer struct {
	grpc.ServerStream
}

func (x *syncUpDataChangeServer) SendAndClose(m *DataChgSummary) error {
	return x.ServerStream.SendMsg(m)
}

func (x *syncUpDataChangeServer) Recv() (*ChatMsg, error) {
	m := new(ChatMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _SyncUp_NodeChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeChgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncUpServer).NodeChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.SyncUp/NodeChange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncUpServer).NodeChange(ctx, req.(*NodeChgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncUp_NodeQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeQryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncUpServer).NodeQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.SyncUp/NodeQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncUpServer).NodeQuery(ctx, req.(*NodeQryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncUp_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncUpServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.SyncUp/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncUpServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SyncUp_serviceDesc = grpc.ServiceDesc{
	ServiceName: "serverpb.SyncUp",
	HandlerType: (*SyncUpServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NodeChange",
			Handler:    _SyncUp_NodeChange_Handler,
		},
		{
			MethodName: "NodeQuery",
			Handler:    _SyncUp_NodeQuery_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _SyncUp_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DataChange",
			Handler:       _SyncUp_DataChange_Handler,
			ClientStreams: true,
		},
	},
}

func init() { proto.RegisterFile("cluster.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 540 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x53, 0x51, 0x6f, 0xd3, 0x30,
	0x10, 0x5e, 0xda, 0xb4, 0x69, 0x2f, 0xa3, 0x14, 0x4b, 0x8c, 0xd2, 0xa7, 0x61, 0x78, 0xe8, 0x53,
	0x1f, 0x8a, 0xd0, 0x24, 0x10, 0x88, 0x2d, 0x7d, 0x60, 0x20, 0xda, 0xce, 0x5b, 0x41, 0xe2, 0x81,
	0xca, 0x4b, 0x4c, 0x5b, 0xa9, 0x89, 0x83, 0xed, 0x20, 0xf5, 0x27, 0xf0, 0x93, 0xf8, 0x77, 0xd8,
	0x4e, 0xd2, 0xac, 0x65, 0xbc, 0xdd, 0x7d, 0x77, 0xdf, 0xdd, 0x77, 0x77, 0x36, 0x3c, 0x08, 0x37,
	0x99, 0x54, 0x4c, 0x0c, 0x53, 0xc1, 0x15, 0x47, 0x2d, 0xc9, 0xc4, 0x2f, 0x26, 0xd2, 0x5b, 0xfc,
	0x06, 0xbc, 0x60, 0x45, 0xd5, 0x67, 0xb9, 0x44, 0x27, 0xd0, 0xcc, 0x34, 0xbe, 0x8e, 0x7a, 0xce,
	0xa9, 0x33, 0x68, 0x90, 0xc2, 0x43, 0x3d, 0xf0, 0x62, 0x26, 0x25, 0x5d, 0xb2, 0x5e, 0x4d, 0x07,
	0xda, 0xa4, 0x74, 0xf1, 0x17, 0xe8, 0x8c, 0xa9, 0xa2, 0xc1, 0x6a, 0x79, 0x9d, 0xc5, 0x31, 0x15,
	0x5b, 0xf4, 0x0c, 0x8e, 0x05, 0x0b, 0xb9, 0x88, 0x16, 0x21, 0xcf, 0x12, 0x65, 0x2b, 0xd5, 0x89,
	0x9f, 0x63, 0x81, 0x81, 0x4c, 0x0a, 0xdb, 0xd0, 0x54, 0xb2, 0x68, 0xa1, 0xd6, 0x71, 0x5e, 0xd3,
	0x25, 0x7e, 0x81, 0xdd, 0x68, 0x08, 0x7f, 0x07, 0x77, 0xc2, 0x23, 0x86, 0xfa, 0xd0, 0xfa, 0xc0,
	0xa5, 0x4a, 0xa8, 0x4e, 0x73, 0x6c, 0xeb, 0xd6, 0xaa, 0xf0, 0x8d, 0x2a, 0x32, 0x0b, 0x66, 0x5c,
	0x28, 0x5b, 0xa1, 0x41, 0x3c, 0x91, 0xbb, 0xe8, 0x14, 0xfc, 0x80, 0x27, 0x92, 0x6f, 0x98, 0x8d,
	0xd6, 0x6d, 0xd4, 0x0f, 0x2b, 0x08, 0xff, 0x71, 0xa0, 0x63, 0x1a, 0x68, 0xe1, 0x84, 0xfd, 0xcc,
	0x98, 0x54, 0xe8, 0x1c, 0xda, 0x3c, 0x65, 0x82, 0xaa, 0x35, 0x4f, 0x6c, 0xaf, 0xce, 0xe8, 0xf9,
	0xb0, 0xdc, 0xd2, 0x70, 0x3f, 0x79, 0x38, 0x2d, 0x33, 0x25, 0xa9, 0x58, 0x08, 0x83, 0x9b, 0xe8,
	0x3c, 0x2b, 0xc7, 0x1f, 0x75, 0xf6, 0xd9, 0xc4, 0xc6, 0xf0, 0x7b, 0x80, 0x8a, 0x8c, 0x7c, 0xf0,
	0xe6, 0x93, 0x4f, 0x93, 0xe9, 0xd7, 0x49, 0xf7, 0x08, 0xb5, 0xc0, 0xfd, 0x38, 0xbd, 0x9c, 0x74,
	0x1d, 0x63, 0x5d, 0xcd, 0x2f, 0x6f, 0xba, 0x35, 0xe4, 0x41, 0xfd, 0x7c, 0x3c, 0xee, 0xd6, 0x0d,
	0x34, 0x26, 0xd3, 0x59, 0xd7, 0xc5, 0xef, 0xe0, 0xe1, 0x4e, 0x8d, 0x4c, 0x75, 0x15, 0x86, 0x10,
	0xb8, 0x3f, 0xe8, 0x7a, 0x63, 0x65, 0xb7, 0x88, 0xb5, 0xd1, 0x13, 0xf0, 0x98, 0x10, 0x8b, 0x58,
	0x2e, 0x8b, 0xa3, 0x35, 0xb5, 0xab, 0xaf, 0x8c, 0x5f, 0xe7, 0xa3, 0x5f, 0x89, 0x6d, 0x39, 0xfa,
	0x00, 0x3c, 0x19, 0x0a, 0x03, 0xda, 0x0a, 0xff, 0x4a, 0x2f, 0xc3, 0xf8, 0x2c, 0xef, 0x6d, 0xb9,
	0x45, 0xef, 0x17, 0xd0, 0x30, 0x90, 0xd4, 0xd4, 0xfa, 0x3d, 0xd4, 0x86, 0x99, 0x5a, 0xe2, 0x57,
	0xe0, 0xcf, 0xd6, 0xc9, 0x6e, 0xd9, 0x5a, 0x70, 0xaa, 0xdd, 0xe2, 0xa6, 0xd6, 0x36, 0x18, 0x8d,
	0x22, 0x51, 0xa8, 0xb5, 0x36, 0xc6, 0x70, 0x9c, 0xd3, 0xaa, 0x41, 0xb5, 0x51, 0xf1, 0xb4, 0x3d,
	0xfa, 0x5d, 0x83, 0xe6, 0xf5, 0x36, 0x09, 0xe7, 0x29, 0x7a, 0x0b, 0x90, 0x3f, 0x47, 0x9a, 0x2c,
	0x19, 0x7a, 0x54, 0x49, 0x29, 0x5e, 0x78, 0xbf, 0x57, 0x41, 0xfb, 0xef, 0x16, 0x1f, 0x0d, 0x1c,
	0x14, 0x00, 0xe4, 0x9b, 0xb5, 0xf4, 0xde, 0xff, 0xae, 0xdf, 0x7f, 0x7a, 0x4f, 0x24, 0x17, 0x88,
	0x8f, 0xd0, 0x05, 0xb4, 0xed, 0x8a, 0x32, 0xa6, 0x7f, 0xc3, 0x41, 0x8d, 0x6a, 0xe7, 0x87, 0x35,
	0xee, 0x6c, 0x54, 0xd7, 0x38, 0x03, 0xd7, 0x8c, 0x8d, 0x1e, 0x57, 0x49, 0x77, 0xb6, 0xd7, 0x3f,
	0x39, 0x84, 0x4b, 0xe2, 0x05, 0x7c, 0xdb, 0x7d, 0xec, 0xdb, 0xa6, 0xfd, 0xe9, 0x2f, 0xff, 0x06,
	0x00, 0x00, 0xff, 0xff, 0x52, 0xcd, 0x33, 0xfb, 0xfa, 0x03, 0x00, 0x00,
}
